# Generated by Django 5.0.1 on 2024-01-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_come', models.DateField()),
                ('data_go', models.DateField()),
                ('guests', models.SmallIntegerField()),
                ('room', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'booking',
            },
        ),
        migrations.AlterField(
            model_name='breakfastmodel',
            name='description',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='breakfastmodel',
            name='price',
            field=models.SmallIntegerField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='breakfastmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
